options:
  collate: utf8_unicode_ci
  charset: utf8
attributes:
  export: all

Profile:
  actAs:
    - Timestampable
  tableName:                    profile
  columns:
    id:                         {type: integer, primary: true, autoincrement: true}
    sf_guard_user_id:           integer(4)
    membership_number:          {type: integer}
    first_name:                 {type: string(100), notnull: true}
    last_name:                  {type: string(100), notnull: true}
    birth_date:                 {type: date}
    documment_type:             {type: enum, values: [ dni, le ], default: dni}
    documment_number:           {type: string(15) }
    phone:                      {type: string(40)}
    movil:                      {type: string(40)}
    email:                      {type: string(60)}
    addres:                     {type: string(100)}
    addres_2:                   {type: string(100)}
    locality_id:                {type: integer}
  relations:
    sfGuardUser:                {local: sf_guard_user_id, foreign: id, foreignType: one, onDelete: CASCADE}

Slides:
  actAs:
    - Timestampable
  tableName:                    slides
  columns:
    id:                         {type: integer, primary: true, autoincrement: true}
    s1:                         {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s2:                         {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s3:                         {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s4:                         {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s5:                         {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s6:                         {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s7:                         {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s8:                         {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s9:                         {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s10:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s11:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s12:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s13:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s14:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s15:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s16:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s17:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s18:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s19:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s20:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s21:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s22:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s23:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    s24:                        {type: enum, values: [ 0,1,2,3,4,5,6,7,8,9,10 ], default: 0}
    r1:                         {type: enum, values: [ 0,1,2,3,4 ], default: 0}
    r2:                         {type: enum, values: [ 0,1,2,3,4 ], default: 0}
    r3:                         {type: enum, values: [ 0,1,2,3,4 ], default: 0}
    r4:                         {type: enum, values: [ 0,1,2,3,4 ], default: 0}
    r5:                         {type: enum, values: [ 0,1,2,3,4 ], default: 0}
    r6:                         {type: enum, values: [ 0,1,2,3,4 ], default: 0}
    r7:                         {type: enum, values: [ 0,1,2,3,4 ], default: 0}
    r8:                         {type: enum, values: [ 0,1,2,3,4 ], default: 0}
    client_id:                  {type: string(255), notnull: true }
    client_poll_id:             {type: date, notnull: true}
